name: Docker Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for Docker image'
        required: true
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
          buildkitd-flags: --allow-insecure-entitlement security.insecure
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          allow: security.insecure
          platforms: linux/arm64
          push: true
          tags: joaoppcastelo/minarca-server-arm64:${{ github.event.inputs.tag || github.ref_name }}